CC = g++
CFLAGS = -std=c++11

all: commands makeinputfile

commands:commands.cpp
			$(CC) -o commands commands.cpp $(CFLAGS)

makeinputfile:makeinputfile.cpp
			$(CC) -o makeinputfile makeinputfile.cpp $(CFLAGS)
